### ISSUE TITLE
Allow the default agent to follow up if slots are missing

### ISSUE THREAD

**Issue by jlpouffier** [OHF-Voice/backlog-issues#11]
> ⚠️ Note. This is a full-blown epic. I am testing the water with this backlog, this task is not meant to be picked up by a single contributor and worked on. It is merely here to provide context for smaller tasks (That will be listed here too)

Bigger context: [Make assist more conversational](https://github.com/OHF-Voice/backlog-issues/issues/2)

# Problem
Some sentences may already convey the intent the user wants to do, but not the details necessary to fulfill the intent.

A good example would be the sentence "Set a timer." 
The intent behind this sentence is definitely `HassStartTimer`, however, we cannot fulfil the intent because we're missing some mandatory slots (In this case, a duration)

# Idea
The idea is to find a mechanism to allow Assist to follow up in these particular cases.
I made a small proof of concept in this branch https://github.com/home-assistant/intents/compare/main...brainstorming-continued-conversation

The gist of it is:

## New folder called `questions`
Where we would store the question and expected answers to these question.
Such as

```yaml
AskForDuration:
  default_question: "For how long?"
  expected_answers:
    - duration:
        - "<timer_duration>"
        - "For <timer_duration>"
```

or
```yaml
AskForArea:
  default_question: "In which do you want to perform this action?"
  expected_answers:
    - area:
        - "in {area}"
        - "{area}"
        - "in the {area}"
```

## Defining these "partial" sentences 

as such:
```yaml
language: "en"
intents:
  HassStartTimer:
      - sentences:
          - "set a timer"
        follow_with:
          question_type: AskForDuration
          allowed_answers:
            - duration
```

and
```yaml
language: "en"
intents:
  HassTurnOn:
      - sentences:
          - "<turn> [(<all>|<the>)] <light> on <here>"
        slots:
          domain: "light"
        follow_with:
          question_type: AskForArea
          allowed_answers:
            - area
```

The structure itself is to be defined, this is mainly an
