### ISSUE TITLE
Intents repo migration

### ISSUE THREAD

**Issue by marcelveldt** [OHF-Voice/backlog-issues#5]
In the process of extending language support for Speech-to-Phrase, I would like to do a better job of tracking which voice commands are supported in the main intents repo. We should be know that (for example) in Greek you can't turn off lights by floor.

The intents.yaml  file will be extended to contain a complete list of slot_combinations  that are supported by the intents in HA core. These slot combinations will be automatically checked against sentence templates for every language so we can provide fine-grained reports on what language leaders are missing.

Additionally, slot combinations that are supported by Speech-to-Phrase will be marked along with the required domains. Eventually, I want to move all of the Speech-to-Phrase sentences into the main intents repo inside its own directory and verify sentence support with our regular tests.

```
HassTurnOn:
  # ...
  slot_combinations:
    - slots:
        - "name"
        - "area"
      example: "turn on the overhead light in the kitchen"
      speech_to_phrase:
        supported: true
        domains:
          - "light"
          - "switch"
          - "media_player"
          - "fan"
          - "input_boolean"
```
